### PR TITLE
Allow Webpack to manage creation of bundle assets and manage file watchers.

### PR DESCRIPTION
**Pull request by davidwarrington**
I tried to use your plugin on a project of mine but found that it creates the concatenated files too early, so my project doesn't detect file changes in watch mode.

I am not an expert with Webpack by any means, so it's entirely possible that there are better ways to go about this.

This refactor adds the output files to Webpacks internal "assets" object. From here Webpack will emit them at the same time as it emits other assets. Becoming part of the Webpack build also allows Webpack to report it in the file list. Theoretically other plugins can modify the assets too if required, as long as they're called at the right time (I'm not certain about this though).

Finally by adding the source files to the `context` and `file` dependency lists Webpack manages watchers for them, removing the need for Chokidar, and since Webpack knows the output files are assets, Webpack includes them in the bundle summary, so Webpack log no longer seems necessary.

### CODE REVIEW

**Comment by joe-damore** [comment]
Hi David, thank you for the PR! I've been meaning to come back and improve on this plugin for a while and just haven't taken the time. I know there were quite a few opportunities for improvement that I've discovered since publishing this, and removing Chokidar was one of them.

I'll take a closer look at your PR later this evening, but judging by your description it sounds like this will be a great change.

Thanks again!

**Comment by davidwarrington** [comment]
Thanks @joe-damore. I'm not too knowledgable regarding Webpack plugins myself, so anything you spot will be greatly appreciated.

**Comment by damorej-at-theinstitutes** [comment]
@davidwarrington This looks and runs great! I'm going to merge this into the `develop` branch for tonight, and during the day tomorrow I'll merge it into `master` and publish version `0.4.0` on NPM which will contain essentially just these changes.

Thanks again for the contribution! This is a slick improvement.

PS Sorry for any confusion, I posted with my personal account earlier today by mistake

**Comment by damorej-at-theinstitutes** [comment]
Hey @davidwarrington, just wanted to send a quick update! I did notice a small issue last night when running the plugin in watch mode; if a source file for a bundle gets modified, all bundles get re-concatenated instead of just the affected bundle.

I believe I can resolve this pretty easily using Webpack's `compilation.fileTimestamps` object in a way that is not destructive to your changes, but I wanted to give you a heads up in case it takes me a little longer to get that release prepared.

Once again, thanks for the contribution!

**Comment by davidwarrington** [comment]
@damorej-at-theinstitutes That's good to know. Cheers. Yeah that's fine. I look forward to seeing how it works

**Pull request merged**
